swagger: "2.0"
info:
  description: "Meetup Management Service API"
  version: "0.1.0"
  title: "Meetup Management Service API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
consumes:
- "application/json"
produces:
- "application/json"
securityDefinitions:
  basicAuth:
    type: basic
security: 
  - basicAuth: []
paths:
  /community/{communityId}/meetup/{meetupId}/draft:
    get:
      tags:
      - Meetup
      summary: "Get meetup draft"
      description: "Get available drafts of meetups"
      operationId: "GetMeetupDrafts"
      parameters: []
      responses:
        200:
          description: "Status 200"
        404:
          description: "Status 404"
    post:
      tags:
      - Meetup
      summary: "Create meetup draft"
      description: "Create new meetup draft."
      operationId: "CreateMeetupDraft"
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/MeetupDraft"
      responses:
        200:
          description: "Status 200"
        400:
          description: "Invalid request parameters"
        404:
          description: "Status 404"
        409:
          description: "Meetup is already exists"
    put:
      tags:
      - Meetup
      summary: "Update meetup draft"
      operationId: "UpdateMeetupDraft"
      parameters: []
      responses:
        200:
          description: "Status 200"
        400:
          description: "Status 400"
        404:
          description: "Status 404"
    delete:
      tags:
      - Meetup
      summary: "Delete meetup draft"
      operationId: "DeleteMeetupDraft"
      parameters: []
      responses:
        200:
          description: "Status 200"
        404:
          description: "Status 404"
    parameters:
    - name: "communityId"
      in: "path"
      required: true
      type: "string"
    - name: "meetupId"
      in: "path"
      required: true
      type: "string"
  /speaker/{speakerId}/draft:
    get:
      tags:
      - Speaker
      summary: "Get speaker draft"
      description: "Get available drafts of speakers"
      operationId: "GetSpeakerDrafts"
      parameters: []
      responses:
        200:
          description: "Status 200"
          schema:
            $ref: "#/definitions/SpeakerDraft"
    post:
      tags:
      - Speaker
      summary: "Create speaker draft"
      description: "Create new meetup draft."
      operationId: "CreateSpeakerDraft"
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/SpeakerDraft"
      responses:
        200:
          description: "Status 200"
    put:
      tags:
      - Speaker
      summary: "Update speaker draft"
      operationId: "UpdateSpeakerDraft"
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/SpeakerDraft"
      responses:
        200:
          description: "Status 200"
    delete:
      tags:
      - Speaker
      summary: "Delete speaker draft"
      operationId: "DeleteSpeakerDraft"
      parameters: []
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "speakerId"
      in: "path"
      required: true
      type: "string"
  /venue/{venueId}/draft:
    get:
      tags:
      - Venue
      summary: "Get venue draft"
      description: "Get available drafts of venue"
      operationId: "GetVenueDrafts"
      parameters: []
      responses:
        200:
          description: "Status 200"
          schema:
            $ref: "#/definitions/VenueDraft"
    post:
      tags:
      - Venue
      summary: "Create venue draft"
      description: "Create new venue draft."
      operationId: "CreateVenueDraft"
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/VenueDraft"
      responses:
        200:
          description: "Status 200"
    put:
      tags:
      - Venue
      summary: "Update speaker draft"
      operationId: "UpdateVenueDraft"
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/VenueDraft"
      responses:
        200:
          description: "Status 200"
    delete:
      tags:
      - Venue
      summary: "Delete venue draft"
      operationId: "DeleteVenueDraft"
      parameters: []
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "venueId"
      in: "path"
      required: true
      type: "string"
  /talk/{talkId}/draft:
    get:
      tags:
      - Talk
      summary: "Get talk draft"
      description: "Get talk draft"
      operationId: "GetTalkDraft"
      parameters: []
      responses:
        200:
          description: "Status 200"
          schema:
            $ref: "#/definitions/VenueDraft"
    post:
      tags:
      - Talk
      summary: "Create talk draft"
      description: "Create new talk draft."
      operationId: "CreateTalkDraft"
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/TalkDraft"
      responses:
        200:
          description: "Status 200"
    put:
      tags:
      - Talk
      summary: "Update speaker draft"
      operationId: "UpdateTalkDraft"
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/TalkDraft"
      responses:
        200:
          description: "Status 200"
    delete:
      tags:
      - Talk
      summary: "Delete talk draft"
      operationId: "DeleteTalkDraft"
      parameters: []
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "talkId"
      in: "path"
      required: true
      type: "string"
  /friend/{friendId}/draft:
    get:
      tags:
      - Friend
      summary: "Get friend draft"
      description: "Get friend draft"
      operationId: "GetFriendDraft"
      parameters: []
      responses:
        200:
          description: "Status 200"
          schema:
            $ref: "#/definitions/FriendDraft"
    post:
      tags:
      - Friend 
      summary: "Create friend draft"
      description: "Create new friend draft."
      operationId: "CreateFriendDraft"
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/FriendDraft"
      responses:
        200:
          description: "Status 200"
    put:
      tags:
      - Friend
      summary: "Update Friend draft"
      operationId: "UpdateFriendDraft"
      consumes: []
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
          $ref: "#/definitions/FriendDraft"
      responses:
        200:
          description: "Status 200"
    delete:
      tags:
      - Friend
      summary: "Delete speaker draft"
      operationId: "DeleteFriendDraft"
      parameters: []
      responses:
        200:
          description: "Status 200"
    parameters:
    - name: "friendId"
      in: "path"
      required: true
      type: "string"
definitions:
  MeetupDraft:
    type: "object"
    required:
    - "Name"
    properties:
      Name:
        type: "string"
        maxLength: 256
      VenueId:
        type: "string"
      TalkIds:
        type: "array"
        items:
          type: "string"
          maxLength: 64
      FriendIds:
        type: "array"
        items:
          type: "string"
          maxLength: 64
    x-restlet:
      section: "DraftModels"
  TalkDraft:
    type: "object"
    properties:
      Title:
        type: "string"
      Description:
        type: "string"
      SpeakerIds:
        type: "array"
        items:
          type: "string"
      SlidesUrl:
        type: "string"
      VideoUrl:
        type: "string"
    x-restlet:
      section: "DraftModels"
  FriendDraft:
    type: "object"
    required:
    - "Name"
    properties:
      Name:
        type: "string"
        maxLength: 256
      Url:
        type: "string"
      Description:
        type: "string"
    x-restlet:
      section: "DraftModels"
  VenueDraft:
    type: "object"
    required:
    - "Name"
    properties:
      Name:
        type: "string"
        maxLength: 256
      Address:
        type: "string"
      MapUrl:
        type: "string"
        maxLength: 2000
    x-restlet:
      section: "DraftModels"
  SpeakerDraft:
    type: "object"
    required:
    - "FirstName"
    - "LastName"
    properties:
      FirstName:
        type: "string"
      LastName:
        type: "string"
      CompanyName:
        type: "string"
      CompanyUrl:
        type: "string"
      Description:
        type: "string"
      BlogsUrl:
        type: "string"
      ContactsUrl:
        type: "string"
      TwitterUrl:
        type: "string"
      HabrUrl:
        type: "string"
      GitHubUrl:
        type: "string"
    x-restlet:
      section: "DraftModels"
x-restlet:
  sections:
    DraftModels: {}
